### ISSUE TITLE
Any chance of making it TB78 compatible?

### ISSUE THREAD

**Issue by lgbaldoni** [Ximi1970/Manually-Sort-Folders#12]
Or would it require a substantial rewrite like you did with Firetray/systray-x ?

**Comment by Ximi1970** [comment]
It would need a substantial rewrite just like ALL add-ons. I am still on the old thunderbird because almost no add-on works anymore. And I am just using 3...This one and an MS exchange add-on is on my wishlist.

**Comment by schneeschmelze** [comment]
Am 04.10.20 um 13:46 Uhr schrieb Maxime Rijnders:
> It would need a substantial rewrite just like ALL add-ons. I am still on
> the old thunderbird because almost no add-on works anymore. And I am
> just using 3...This one and an MS exchange add-on is on my wishlist.


You might like to know that MSF has indeed been adapted to TB78. You can
find the new version on the ATN platform. It works fine for me.

**Comment by lgbaldoni** [comment]
Yeah, that's great indeed!

**Comment by Ximi1970** [comment]
Did not have much time to dive into this past months, will check it out! Thnx.

**Comment by despecial** [comment]
Not completely. 

It‘s not possible to change the account order (local folder before accounts)

> > It would need a substantial rewrite just like ALL add-ons. I am still on
> > the old thunderbird because almost no add-on works anymore. And I am
> > just using 3...This one and an MS exchange add-on is on my wishlist.
> 
> 
> You might like to know that MSF has indeed been adapted to TB78. You can
> find the new version on the ATN platform. It works fine for me.
> —

**Comment by lgbaldoni** [comment]
@despecial I can live with that.
