### ISSUE TITLE
Adding a new email account causes "Local Folders" position to drop if moved.

### ISSUE THREAD

**Issue by GypsySpellweaver** [Ximi1970/Manually-Sort-Folders#2]
Current setup:

> Linux (openSUSE Leap 15.0)
> Thunderbird 60.2.1 (64-bit)
> Manually sort folders 1.2.0pre2

I have set "Local Folders" as the first/default account with other accounts in my order after that.
If I add a new email account, that account will become the new first account and "Local Folders" is returned to the bottom of the list. Any additional accounts added after that will be added to the end, _before_ the "Local Folders".

Applying the sort again and adding another account will repeat the process of moving the "Local Folders" to the end of the list and placing the new account as the first account, and additional accounts at the end just before the "Local Folders"

This happens with both POP3 and IMAP accounts being added.

The remainder of the sorting is not affected, and it does not happen if "Local Folders" is not first.

If there is any other information I can provide, or tests to run, I am willing to help.

**Comment by despecial** [comment]
Simple question: did you restart TB after changing the settings?

**Comment by Ximi1970** [comment]
I can confirm the problem. Looks like adding an account will reset the sort and default account setting.

**Comment by GypsySpellweaver** [comment]
@despecial  That's affirmative. TB was restarted to apply the sort each time a new sorting was created. TB was also started after adding one new account, and then the un-sorting is seen. If adding one new account the effect will not be seen until a restart of TB, prior to the restart the new account will be on the bottom and "Local Folders" will still be at the top. If, however you add a second email before doing the restart, the observed effect will happen as soon as the second process is complete and the account is added to the list.

**Comment by GypsySpellweaver** [comment]
Further experiments: After adding one account and then reopening the "Account Settings" dialog, the un-sorted effect is evident in the account listing, new account at the top and "Local Folders" at the bottom. Separate experiment of adding one account, using the link on the main panel when an account is selected rather than a mailbox, (not using the "Account Settings" dialog), after the account is added and opening the "Manually sort folders" dialog, the un-sorted effect is noticed. Closing that dialog, with or without making any changes, causes the account list to refresh and also show the un-sorted effect, without restarting TB. (Note: each experiment involves adding a never-before-added account to avoid any cache or latent data tainting the experiment.)

**Comment by Ximi1970** [comment]
I created a new pre-release. After adding one or more accounts you still need to restart TB to restore the sorting order.

**Comment by smallersign** [comment]
Hello, where we can see changelog? Like what's new in v1.2.0pre3? You are updating changelog also?

**Comment by Ximi1970** [comment]
Sorry, totally forgot the changelog..
The new version should fix the Local Folders problem.

**Comment by GypsySpellweaver** [comment]
Looks like it passes every sequence I can thing to throw at it. Adding an account, then opening (or reopening) the "Account Settings" dialog will show the new account at the top, and "Local Folders" at the bottom. A restart, however, and then the user-specified sort order is re-enforced.

If adding only one account, and the "Account Settings" dialog is not accessed prior to a restart, the order appears to remain stable in the "Accounts" panel. Seems unlikely that it's very often a user would add more than one account at a time, after initial setup. Even though TB has "lost" the user-specified sort order temporarily, it will remain transparent to the user, and the restart will establish the correct order, with the user never noticing any switch.

I was lucky enough to catch the reordering in progress on a restart while the CPU was otherwise busy and the process was slowed down enough to see it happening. Entertainment in its own right. :)

Seems like a closed issue to me.

Thanks.

**Comment by Ximi1970** [comment]
Thanks for testing !
