### ISSUE TITLE
Thunderbird Bug report

### ISSUE THREAD

**Issue by kotaro366** [Ximi1970/Manually-Sort-Folders#3]
I will report it as a bug.
If you add a new account, even if you see all the subfolders in the new account, reopening Thunderbird will close the subfolder (Tree) of the new account.
Even if you manually open the subfolder (Tree), when you restart Thunderbird, the subfolder (tree) will also be closed.
v1.2.0 pre 3 - If you disable Thunderbird 60+ release you will see a subfolder (Tree) without problems

(Second bug)
・Even if you set the startup folder to the custom folder "Inbox" with the additional setting, local page will appear on the right side for a moment when Thunderbird starts up.
There was no problem until Thunderbird 52.9.1.

**Comment by Ximi1970** [comment]
@kotaro366, I cannot not reproduce the problems you have.
Can you tell me the setup you are using? (Thunderbird version, OS, other Thunderbird plugins used)

I only know that Thunderbird will have a problem with the tree state when it crashes or does not quit normally. It will not store the latest state in that case.
You really need to quit the application to store the tree state....(Menu->File->Quit)

**Comment by kotaro366** [comment]
It is the environment I am using.
· Thunderbird 60.2.1 (64bit) The same bug will appear even if 32bit is used.
· Windows 10 (64 bit) 1803

plugins
    Manually-Sort-Folders v1.2.0 pre 3 - Thunderbird 60+ release only
　　Reinstalling this add-on has emptied the folder.

**Comment by kotaro366** [comment]
Excuse me.
The folder will not be empty but the add-on panel will be empty

**Comment by kotaro366** [comment]
I'm sorry
×Folder (Mistake)
○(correct)The add-on panel will be blank

**Comment by Ximi1970** [comment]
Issue at protz: https://github.com/protz/Manually-Sort-Folders/issues/67

Does it look like this? Are both marked boxes empty? Are you using Japanese characters? (...looking at your user name :-) )

**Comment by kotaro366** [comment]
・? The place of the mark is displayed
・The box under the sort accounts page is blank
・User name is English

(However, Windows 10 is Japanese version)

**Comment by Ximi1970** [comment]
I created a new user on my Windows 10 Pro, installed the japanese language pack and the japanese Thunderbird version. And everything is just working fine...

Can you also try to create a new user on your machine and test Thunderbird with the new account?

Trying some Google Translation magic:

私はWindows 10 Proで新しいユーザーを作成しました, 日本語の文字パックと日本版のThunderbirdをインストールしました,
すべて順調 ...

あなたのマシンに新しいユーザーを作りましょう
Thunderbirdを新しいアカウントでテストする

Watashi wa u~indōzu 10 Pro de atarashī yūzā o sakusei shimashita, Nihongo no moji pakku to nipponban no sandābādo o insutōru shimashita,
Subete junchō...
Anata no mashin ni atarashī yūzā o tsukurimashou
Sandābādo o atarashī akaunto de tesuto suru

**Comment by kotaro366** [comment]
Thank you for confirmation
I will try again.

Thank you very much

**Comment by beetram** [comment]
The second problem of the first question is not solved
I feel that it is a problem

「Even if you set the startup folder to the custom folder "Inbox" with the additional setting, 
local page will appear on the right side for a moment when Thunderbird starts up.
There was no problem until Thunderbird 52.9.1」

The local screen is temporarily displayed on the right side at startup. Although it is a moment, the local screen was completely skipped at 52.9.1, and the reception screen was displayed immediately.

Do you have any plans to fix it?

Windows10 64bit 1803 (ja)   Thunderbird 60.3.0 64bit
Manually-Sort-Folders v1.2.0 pre 3  

Thank you

**Comment by Ximi1970** [comment]
I checked the second bug, but this is not caused by Manually-Sort_folders. Even without the add-on the local page will appear for a moment. It happens both in the 32bit and 64bit of Tb60+.
Looks like a bug in Thunderbird.

**Comment by beetram** [comment]
I disabled the add-on and confirmed it.
As I got an answer I understood it as a bug in Thunderbird.
Thank you for confirmation.

**Comment by kotaro366** [comment]
Thank you for confirming various things.
Please close this thread.
 Thank you very much.

**Comment by beetram** [comment]
close #3
