### ISSUE TITLE
1.2.0pre3 account sorting is blank

### ISSUE THREAD

**Issue by bubingator** [Ximi1970/Manually-Sort-Folders#7]
TB 60.3.3 x32, Manually Sort Folders 1.2.0pre3 debug version. Account sorting is blank. In debug console I see this:
```
NS_ERROR_UNEXPECTED: Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.getStringPref]  ui.js:431
	accounts_on_load/servers< chrome://tbsortfolders/content/ui.js:431:37
	map self-hosted:285:17
	accounts_on_load chrome://tbsortfolders/content/ui.js:431:17
	on_load chrome://tbsortfolders/content/ui.js:296:3
	onload chrome://tbsortfolders/content/tbsortfolders.xul:1:1
	oncommand chrome://messenger/content/messenger.xul:1:1
```
with 1.2.0pre2 version acc sorting working.

**Comment by Ximi1970** [comment]
Strange...somehow the plugin is not able to read a user_pref(mail.acount.accountxx..) line from the prefs.js file when debug is enabled. But there are no debug lines in that function.

Could you post the following "user_pref" lines from the prefs.js thunderbird configuration file:
If you are using Linux you can find the file in ~/.thunderbird/..profile../ directory
If you are using Windows, it is in: c:\Users\ ..user..\AppData\Roaming\Thunderbird\Profiles\ ..profile..\

The line:
user_pref("mail.accountmanager.accounts", .....

All the lines (with xx a number from 1 to 99?):
user_pref("mail.account.accountxx.server", ....
user_pref("mail.account.accountxx.identities", ....

Thank you.

**Comment by bubingator** [comment]
```
user_pref("mail.account.account10.identities", "id8");
user_pref("mail.account.account10.server", "server9");
user_pref("mail.account.account2.server", "server2");
user_pref("mail.account.account3.identities", "id2");
user_pref("mail.account.account3.server", "server3");
user_pref("mail.account.account4.identities", "id3");
user_pref("mail.account.account4.server", "server4");
user_pref("mail.account.account5.identities", "id1");
user_pref("mail.account.account5.server", "server1");
user_pref("mail.account.account6.identities", "id4");
user_pref("mail.account.account6.server", "server5");
user_pref("mail.account.account7.identities", "id5");
user_pref("mail.account.account7.server", "server6");
user_pref("mail.account.account8.identities", "id6");
user_pref("mail.account.account8.server", "server7");
user_pref("mail.account.account9.identities", "id7");
user_pref("mail.account.account9.server", "server8");
user_pref("mail.account.lastKey", 10);
user_pref("mail.accountmanager.accounts", "account10,account6,account7,account4,account5,account3,account8,account9,account2");
user_pref("mail.accountmanager.defaultaccount", "account10");
user_pref("mail.accountmanager.localfoldersserver", "server2");
```

**Comment by bubingator** [comment]
I think I solved the problem. I just deleted three strings with *extensions.tbsortfolders* from perf.js file. Now MSF works.

**Comment by Ximi1970** [comment]
Thank you for the debugging I will have a look on how these prefs could corrupt the pref.js file.
